accessibleBIM/urls.py
from allauth.urls import provider_urlpatterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from accessibleBIM import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/', include('allauth.socialaccount.urls')),
    path('accounts/', include(provider_urlpatterns)),
] + i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('front.urls')),
    path('', include('accounts.urls')),
    path('moderator/', include('modules.urls')),
    path('moderator/', include('progress.urls')),
    path('moderator/', include('step.urls')),
    path('moderator/', include('subscription.urls')),
    path('quiz_bim/', include('quiz_bim.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('statistics/', include('reports.urls')),
    path('moderator/', include('content.urls')),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "front.views.errors_handler.page_not_found_view"
handler403 = "front.views.errors_handler.permission_denied_view"
handler500 = "front.views.errors_handler.server_error_view"

quiz_bim/urls.py
from django.urls import path

from quiz_bim.views.answer_bim_views import AnswerBimFormDetailView, AnswerBimFormCreateView, AnswerBimFormUpdateView, \
    AnswerBimFormDeleteView
from quiz_bim.views.question_bim_views import QuestionBimFormDetailView, QuestionBimFormCreateView, \
    QuestionBimFormUpdateView, QuestionBimFormDeleteView
from quiz_bim.views.take_quiz_views import TakeQuizView, QuestionsCompletionView, UserAnswerAPIView, QuizResultView
from quiz_bim.views.quiz_bim_views import QuizBimListView, QuizBimCreateView, QuizBimDetailView, QuizBimUpdateView, \
    QuizBimDeleteView

app_name = 'quiz_bim'

urlpatterns = [
    path('', QuizBimListView.as_view(), name='quizbim_list'),
    path('quiz/create/', QuizBimCreateView.as_view(), name='quizbim_create'),
    path('quiz/<int:pk>/', QuizBimDetailView.as_view(), name='quizbim_detail'),
    path('quiz/<int:pk>/update/', QuizBimUpdateView.as_view(), name='quizbim_update'),
    path('quiz/<int:pk>/delete/', QuizBimDeleteView.as_view(), name='quizbim_delete'),

    path('quiz/<int:tpk>/question_bim/detail/<int:qpk>/', QuestionBimFormDetailView.as_view(),
         name='questionbim_htmx_detail'),
    path('quiz/question_bim/create/', QuestionBimFormCreateView.as_view(), name='questionbim_htmx_create'),
    path('quiz/<int:tpk>/question_bim/update/<int:qpk>/', QuestionBimFormUpdateView.as_view(),
         name='questionbim_htmx_update'),
    path('quiz/<int:tpk>/question_bim/delete/<int:qpk>/', QuestionBimFormDeleteView.as_view(),
         name='questionbim_htmx_delete'),

    path('question_bim/<int:qpk>/answer_bim/detail/<int:apk>/', AnswerBimFormDetailView.as_view(),
         name='answerbim_htmx_detail'),
    path('question_bim/<int:pk>/answer_bim/create/', AnswerBimFormCreateView.as_view(), name='answerbim_htmx_create'),
    path('question_bim/<int:qpk>/answer_bim/update/<int:apk>/', AnswerBimFormUpdateView.as_view(),
         name='answerbim_htmx_update'),
    path('question_bim/<int:qpk>/answer_bim/delete/<int:apk>/', AnswerBimFormDeleteView.as_view(),
         name='answerbim_htmx_delete'),

    path('take-quiz/<int:pk>/', TakeQuizView.as_view(), name='take_quiz'),
    path('quiz-completion/<int:pk>/', QuestionsCompletionView.as_view(), name='test_completion'),
    path('api/answer/<int:pk>', UserAnswerAPIView.as_view(), name='user_answer'),
    path('quiz-result/<int:pk>', QuizResultView.as_view(), name='test_result'),
]

step/urls.py
from django.urls import path

from step.views.file_view import FileListView, FileDetailView, FileCreateView, FileUpdateView, FileDeleteView
from step.views.step_view import StepListView, StepDetailView, StepUpdateView, StepDeleteView, StepCreateView
from step.views.text_view import TextListView, TextDetailView, TextCreateView, TextUpdateView, TextDeleteView
from step.views.video_view import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView

app_name = 'step'

urlpatterns = [
    path('steps/', StepListView.as_view(), name='stepmodel_list'),
    path('step/<int:pk>/', StepDetailView.as_view(), name='stepmodel_detail'),
    path('step/create/text/', StepCreateView.as_view(), name='stepmodel_text_create'),
    path('step/create/video/', StepCreateView.as_view(), name='stepmodel_video_create'),
    path('step/create/quiz/', StepCreateView.as_view(), name='stepmodel_quiz_create'),
    path('step/<int:pk>/update/', StepUpdateView.as_view(), name='stepmodel_update'),
    path('step/<int:pk>/delete/', StepDeleteView.as_view(), name='stepmodel_delete'),

    path('videos/', VideoListView.as_view(), name='videomodel_list'),
    path('video/<int:pk>/', VideoDetailView.as_view(), name='videomodel_detail'),
    path('video/create/', VideoCreateView.as_view(), name='videomodel_create'),
    path('video/<int:pk>/update/', VideoUpdateView.as_view(), name='videomodel_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='videomodel_delete'),

    path('texts/', TextListView.as_view(), name='textmodel_list'),
    path('text/<int:pk>/', TextDetailView.as_view(), name='textmodel_detail'),
    path('text/create/', TextCreateView.as_view(), name='textmodel_create'),
    path('text/<int:pk>/update/', TextUpdateView.as_view(), name='textmodel_update'),
    path('text/<int:pk>/delete/', TextDeleteView.as_view(), name='textmodel_delete'),

    path('files/', FileListView.as_view(), name='filemodel_list'),
    path('file/<int:pk>/', FileDetailView.as_view(), name='filemodel_detail'),
    path('file/create/', FileCreateView.as_view(), name='filemodel_create'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='filemodel_update'),
    path('file/<int:pk>/delete/', FileDeleteView.as_view(), name='filemodel_delete')
]

step/models/text.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from modules.models import AbstractModel


class TextModel(AbstractModel):
    text_title = models.CharField(max_length=250, blank=True, null=True, verbose_name=_('Text title'))
    text_description = models.CharField(max_length=1500, blank=True, null=True, verbose_name=_('Text description'))
    content = models.TextField(max_length=100000, blank=True, null=True, verbose_name=_('Text content'))

    def get_absolute_url(self):
        return reverse("step:text_list")

    def __str__(self):
        return f'Текст {self.id} {self.text_title}'

    class Meta:
        db_table = 'texts'
        verbose_name = _('Text')
        verbose_name_plural = _('Texts')

quiz_bim/forms/answer_bim_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

from quiz_bim.models.answer_bim import AnswerBim


class AnswerBimForm(forms.ModelForm):

    class Meta:
        model = AnswerBim
        fields = ['answer', 'is_correct']
        labels = {
            'answer': _('Answer'),
            'is_correct': _('Right answer'),

        }

quiz_bim/forms/question_bim_form.py
from django import forms
from django.utils.translation import gettext_lazy as _
from quiz_bim.models.question_bim import QuestionBim


class QuestionBimForm(forms.ModelForm):

    class Meta:
        model = QuestionBim
        fields = ['title']
        labels = {
            'title': _('Enter question'),
        }

quiz_bim/forms/quiz_bim_for_step_form.py
from django import forms

from quiz_bim.models.quiz_bim import QuizBim


class QuizBimForStepForm(forms.ModelForm):

    class Meta:
        model = QuizBim
        fields = ['title']
        widgets = {
            'questions_qty': forms.NumberInput(attrs={'value': 0}),
        }

quiz_bim/forms/quiz_bim_form.py
from django import forms
from django.utils.translation import gettext_lazy as _
from quiz_bim.forms.quiz_bim_for_step_form import QuizBimForStepForm


class QuizBimForm(QuizBimForStepForm):
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError(_('Please enter title'))
        return title

quiz_bim/forms/test_bim_form.py
from django import forms
from quiz_bim.models.test_bim import QuizBim
from django.forms import widgets


class TestBimForm(forms.ModelForm):

    class Meta:
        model = QuizBim
        fields = '__all__'
        labels = {
            'title': 'Тема тестирования',
            'questions_qty': 'Количество вопросов в тесте',
        }
        widgets = {
            'test_title': widgets.TextInput(attrs={'class': 'form-control'}),
            'questions_qty': widgets.NumberInput(attrs={'class': 'form-control'}),
        }

quiz_bim/views/answer_bim_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import FormMixin

from quiz_bim.forms.answer_bim_form import AnswerBimForm
from quiz_bim.models import AnswerBim, QuestionBim
from quiz_bim.validators import validate_answer


class AnswerBimFormCreateView(PermissionRequiredMixin, View):
    def get(self, request, pk=None, *args, **kwargs):
        question = get_object_or_404(QuestionBim, pk=pk)
        forms = AnswerBimForm()
        # Пока не реализовано (идея такова что приходит pk и данное кол-во форм создается)
        # if not pk:
        #     forms = AnswerBimForm()
        #
        # else:
        #     forms = []
        #     for i in range(0, int(pk)):
        #         forms.append(AnswerBimForm())
        context = {
            'forms': forms,
            'question': question
        }

        return render(request, "quiz_bim/answer_bim/answer_bim_form.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class AnswerBimFormDetailView(PermissionRequiredMixin, View):
    def get(self, request, qpk, apk, *args, **kwargs):
        answer = get_object_or_404(AnswerBim, id=apk)
        context = {
            'answer': answer
        }
        return render(request, "quiz_bim/answer_bim/answer_bim_detail.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class AnswerBimFormUpdateView(PermissionRequiredMixin, View, FormMixin):
    form = None

    def get(self, request, qpk, apk, *args, **kwargs):
        answer = get_object_or_404(AnswerBim, id=apk)
        form = AnswerBimForm(request.POST or None, instance=answer)
        context = {
            "forms": form,
            "answer": answer
        }
        return render(request, "quiz_bim/answer_bim/answer_bim_form.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def post(self, request, *args, **kwargs):
        answer = get_object_or_404(AnswerBim, id=kwargs["apk"])
        form = AnswerBimForm(request.POST or None, instance=answer)
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        if not form.is_valid():
            return render(self.request, "quiz_bim/answer_bim/answer_bim_form.html", context={
                "forms": [form],
            })
        form.save(commit=False)
        form.question_bim = get_object_or_404(QuestionBim, pk=kwargs["qpk"])
        answer_content = form.cleaned_data["answer"]
        is_correct = form.cleaned_data["is_correct"]
        error_messages = validate_answer(form, form.question_bim, answer_content, is_correct, update=True)
        if error_messages:
            return render(self.request, "quiz_bim/answer_bim/answer_bim_form.html", context={
                "forms": form,
                "error_messages": error_messages,
                "question": form.question_bim,
                "answer": answer
            })
        form.save()
        return redirect("quiz_bim:answerbim_htmx_detail", qpk=kwargs['qpk'], apk=kwargs['apk'])


class AnswerBimFormDeleteView(PermissionRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        answer = get_object_or_404(AnswerBim, id=kwargs['apk'])
        answer.delete()
        return HttpResponse("")

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

quiz_bim/views/question_bim_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import FormMixin

from quiz_bim.forms.question_bim_form import QuestionBimForm
from quiz_bim.models import QuestionBim, AnswerBim, QuizBim


class QuestionBimFormCreateView(PermissionRequiredMixin, View):
    def get(self, request, pk=None, *args, **kwargs):
        form = QuestionBimForm()
        context = {
            'form': form
        }
        return render(request, "quiz_bim/question_bim/question_bim_form.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class QuestionBimFormDetailView(PermissionRequiredMixin, View):
    def get(self, request, tpk, qpk, *args, **kwargs):
        question = get_object_or_404(QuestionBim, id=qpk)
        answers = AnswerBim.objects.all()
        context = {
            'question': question,
            'answers': answers
        }
        return render(request, "quiz_bim/question_bim/question_bim_detail.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class QuestionBimFormUpdateView(PermissionRequiredMixin, View, FormMixin):
    form = None

    def get(self, request, tpk, qpk, *args, **kwargs):
        question = get_object_or_404(QuestionBim, id=qpk)
        form = QuestionBimForm(request.POST or None, instance=question)
        context = {
            "form": form,
            "question": question
        }
        return render(request, "quiz_bim/question_bim/question_bim_form.html", context)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def post(self, request, *args, **kwargs):
        question = QuestionBim.objects.get(id=kwargs['qpk'])
        form = QuestionBimForm(request.POST or None, instance=question)
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        if form.is_valid():
            form.save()
            return redirect("quiz_bim:questionbim_htmx_detail", tpk=kwargs['tpk'], qpk=kwargs['qpk'])
        else:
            context = {
                "forms": form,
                "question": question
            }
            return render(request, "quiz_bim/question_bim/question_bim_form.html", context)


class QuestionBimFormDeleteView(PermissionRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        question = get_object_or_404(QuestionBim, id=kwargs['qpk'])
        quiz = get_object_or_404(QuizBim, id=kwargs['tpk'])
        questions_qty = QuestionBim.objects.filter(test_bim=quiz).count()
        questions_qty -= 1
        quiz.questions_qty = questions_qty
        question.delete()
        quiz.save()
        return HttpResponse("")

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

quiz_bim/views/test_bim_views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from quiz_bim.models.test_bim import QuizBim
from quiz_bim.forms.test_bim_form import TestBimForm


class TestsBimListView(ListView):
    model = QuizBim
    template_name = 'quiz_bim/test_bim/test_bim_list.html'
    context_object_name = 'tests'



class TestBimDetailView(DetailView):
    queryset = QuizBim.objects.all()
    template_name = "quiz_bim/test_bim/test_bim_detail.html"
    context_object_name = 'test'

    def get_context_data(self, **kwargs):
        questions = self.object.question_bim.all()
        kwargs['questions'] = questions
        return super().get_context_data(**kwargs)


class TestBimCreateView(CreateView):
    form_class = TestBimForm
    template_name = "quiz_bim/test_bim/test_bim_create.html"

    def get_success_url(self):
        return reverse("quiz_bim:test_detail", kwargs={"pk": self.object.pk})





class TestBimUpdateView(UpdateView):
    model = QuizBim
    form_class = TestBimForm
    template_name = 'quiz_bim/test_bim/test_bim_update.html'
    success_url = reverse_lazy('quiz_bim:tests_list')
    context_object_name = 'test'


class TestBimDeleteView(DeleteView):
    model = QuizBim
    context_object_name = 'test'
    template_name = 'quiz_bim/test_bim/test_bim_delete.html'
    success_url = reverse_lazy('quiz_bim:tests_list')

templates/quiz_bim/quiz_bim/quiz_bim_create.html
{% extends 'moderator_page.html' %}
{% load view_breadcrumbs i18n %}
{% block title %}{% trans 'Add test' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
        <div class="card mb-5">
            <div class="card-body">
                <div>
                    <div class="container my-5">
                        <div class="card-header">
                            <h2>{% trans 'Add test' %}:</h2>
                        </div>
                        <div>
                            {% trans 'Add' as button_text_add %}
                            {% include "partials/form.html" with button_text=button_text_add %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/quiz_bim/quiz_bim/quiz_bim_delete.html
{% extends 'moderator_page.html' %}
{% load static view_breadcrumbs i18n %}
{% block title %}{% trans 'Delete test' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card">
        <div class="card-body">
            {% if steps %}
                <h5 class="card-text">{% trans 'This test is used in the lessons below' %}:</h5>
                {% for step in steps %}
                    <a href="{% url "step:stepmodel_update" step.id %}">{{ step.title }}</a>
                    </br>
                {% endfor %}
                <h5 class="card-text my-2">
                    {% trans 'In order to delete this test you should change related tests in the lessons above.' %}
                </h5>
            {% else %}
                <p class="card-text">
                    {% blocktrans with title=test.title %}
                    Are you sure you want to delete the test
                    <span class="text-danger"> {{ title }}</span>?
                    {% endblocktrans %}
                </p>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" name="delete" class="btn btn-danger me-4" value="yes">{% trans 'Yes' %}</button>
                    <a href="#" class="btn btn-secondary
                    mx-3" id="cancel-button">{% trans 'No' %}</a>
                </form>
            {% endif %}
        </div>
    </div>
    <script src="{% static 'js/delete_button_func.js' %}"></script>
{% endblock %}

templates/quiz_bim/quiz_bim/quiz_bim_detail.html
{% extends 'moderator_page.html' %}
{% load view_breadcrumbs i18n %}
{% load static %}
{% block title %}{{ test.title }}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <div class="card-header">
                    <h3 class="mb-3">{% trans 'Test' %} "{{ test.title }}"</h3>
                    <h4 id="questions_qty">{% trans 'Questions quantity' %}: {{ test.questions_qty }} </h4>
                </div>
                <div class="d-flex flex-column align-items-start my-3">
                    <a class="btn btn-primary mb-2" hx-get="{% url 'quiz_bim:questionbim_htmx_create' %}"
                       hx-target="#questionforms" hx-swap="beforeend" role="button" id="create_question">
                        {% trans 'Add new question' %}</a>
                    <a class="btn btn-primary" href="{% url 'quiz_bim:quizbim_update' pk=test.pk %}" role="button">
                        {% trans 'Edit' %}</a>
                </div>
                <div class="table-responsive">
                    <div class="d-flex justify-content-center my-3">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination" id="pagination-block">
                            </ul>
                        </nav>
                    </div>
                </div>
                <div id="questionforms" class="col"></div>
                <div class="questions-container">
                    {% for question in questions %}
                        <div id="question_block_{{ forloop.counter }}" class="question-block mb-4">
                            {% include "quiz_bim/question_bim/question_bim_detail.html" %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static "js/questions_pagination.js" %}"></script>
{% endblock %}

templates/quiz_bim/quiz_bim/quiz_bim_list.html
{% extends 'moderator_page.html' %}
{% load view_breadcrumbs i18n %}
{% block title %}{% trans 'Tests list' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card mb-5">
        <div class="card-body">
            <div class="card-header">
                <h2>{% trans 'Tests list' %}</h2>
            </div>
            <a class="btn btn-primary my-3" href="{% url "quiz_bim:quizbim_create" %}">{% trans 'Add' %}</a>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>{% trans 'Title' %}</th>
                    <th class="text-end">{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for test in tests|dictsort:"id" %}
                    <tr>
                        <td>{{ test.id }}</td>
                        {% if request.user.is_authenticated %}
                            <td><a href="{% url 'quiz_bim:quizbim_detail' pk=test.pk %}">{{ test.title }}</a></td>
                        {% endif %}
                        <td class="text-end">
                            {% if perms.step.change_textmodel %}
                                <a href="{% url 'quiz_bim:quizbim_update' pk=test.pk %}"
                                   class="btn btn-info btn-sm mb-2">{% trans 'Change' %}</a>
                            {% endif %}
                            {% if perms.step.delete_textmodel %}
                                <a href="{% url 'quiz_bim:quizbim_delete' pk=test.pk %}"
                                   class="btn btn-danger btn-sm mb-2 ms-2">{% trans 'Delete' %}</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/quiz_bim/quiz_bim/quiz_bim_update.html
{% extends 'moderator_page.html' %}
{% load view_breadcrumbs i18n %}
{% block title %}{% trans 'Edit test' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card mb-5">
        <div class="card-body">
            <div>
                <div class="container my-5">
                    <div class="card-header">
                        <h2>{% trans 'Edit test' %}:</h2>
                    </div>
                    <div>
                        {% trans 'Edit' as button_text_edit %}
                        {% include "partials/form.html" with button_text=button_text_edit %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}