accessibleBIM/urls.py
from allauth.urls import provider_urlpatterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from accessibleBIM import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/', include('allauth.socialaccount.urls')),
    path('accounts/', include(provider_urlpatterns)),
] + i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('front.urls')),
    path('', include('accounts.urls')),
    path('moderator/', include('modules.urls')),
    path('moderator/', include('progress.urls')),
    path('moderator/', include('step.urls')),
    path('moderator/', include('subscription.urls')),
    path('quiz_bim/', include('quiz_bim.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('statistics/', include('reports.urls')),
    path('moderator/', include('content.urls')),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "front.views.errors_handler.page_not_found_view"
handler403 = "front.views.errors_handler.permission_denied_view"
handler500 = "front.views.errors_handler.server_error_view"

modules/urls.py
from django.urls import path

from modules.views.course_preview import CoursePreviewView
from modules.views.modules import ModeratorView

from modules.views.modules import ModulesListView, ModuleCreateView, ModuleDetailView, ModuleDeleteView, \
    ModuleUpdateView

from modules.views.teachers import TeachersListView, TeacherCreateView, TeacherDetailView, TeacherDeleteView, \
    TeacherUpdateView

from modules.views.course_target import CourseTargetsListView, CourseTargetCreateView, CourseTargetDetailView, \
    CourseTargetDeleteView, CourseTargetUpdateView

from modules.views.courses import CoursesListView, CourseCreateView, CourseDetailView, CourseDeleteView, \
    CourseUpdateView, CourseChangeChaptersOrderView

from modules.views.chapters import ChaptersListView, ChapterCreateView, ChapterDetailView, ChapterDeleteView, \
    ChapterUpdateView, ChapterChangeStepsOrderView

app_name = 'modules'

urlpatterns = [
    path('', ModeratorView.as_view(), name='moderator_page'),
    path('modules/', ModulesListView.as_view(), name="modulemodel_list"),
    path('module/create/', ModuleCreateView.as_view(), name="modulemodel_create"),
    path('module/<int:pk>/', ModuleDetailView.as_view(), name="modulemodel_detail"),
    path('module/<int:pk>/update/', ModuleUpdateView.as_view(), name="modulemodel_update"),
    path('module/<int:pk>/delete/', ModuleDeleteView.as_view(), name="modulemodel_delete"),

    path('teachers/', TeachersListView.as_view(), name="teachermodel_list"),
    path('teacher/create/', TeacherCreateView.as_view(), name="teachermodel_create"),
    path('teacher/<int:pk>/detail/', TeacherDetailView.as_view(), name="teachermodel_detail"),
    path('teacher/<int:pk>/update/', TeacherUpdateView.as_view(), name="teachermodel_update"),
    path('teacher/<int:pk>/delete/', TeacherDeleteView.as_view(), name="teachermodel_delete"),

    path('course_targets/', CourseTargetsListView.as_view(), name="coursetargetmodel_list"),
    path('course_target/create/', CourseTargetCreateView.as_view(), name="coursetargetmodel_create"),
    path('course_target/<int:pk>/detail/', CourseTargetDetailView.as_view(), name="coursetargetmodel_detail"),
    path('course_target/<int:pk>/update/', CourseTargetUpdateView.as_view(), name="coursetargetmodel_update"),
    path('course_target/<int:pk>/delete/', CourseTargetDeleteView.as_view(), name="coursetargetmodel_delete"),
    path('course/<int:pk>/change_chapters_order', CourseChangeChaptersOrderView.as_view(),
         name="change_chapters_order"),

    path('courses/', CoursesListView.as_view(), name="coursemodel_list"),
    path('course/create/', CourseCreateView.as_view(), name="coursemodel_create"),
    path('course/<int:pk>/detail/', CourseDetailView.as_view(), name="coursemodel_detail"),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name="coursemodel_update"),
    path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name="coursemodel_delete"),
    path('course/<int:pk>/change_chapters_order', CourseChangeChaptersOrderView.as_view(),
         name="change_chapters_order"),
    path('course/<int:course_pk>/chapter/<int:chapter_pk>/preview/', CoursePreviewView.as_view(), name="coursemodel_preview"),

    path('chapters/', ChaptersListView.as_view(), name="chaptermodel_list"),
    path('chapter/create/', ChapterCreateView.as_view(), name="chaptermodel_create"),
    path('chapter/<int:pk>/detail/', ChapterDetailView.as_view(), name="chaptermodel_detail"),
    path('chapter/<int:pk>/update/', ChapterUpdateView.as_view(), name="chaptermodel_update"),
    path('chapter/<int:pk>/delete/', ChapterDeleteView.as_view(), name="chaptermodel_delete"),
    path('chapter/<int:pk>/change_steps_order', ChapterChangeStepsOrderView.as_view(),
         name="change_steps_order"),
]

step/urls.py
from django.urls import path

from step.views.file_view import FileListView, FileDetailView, FileCreateView, FileUpdateView, FileDeleteView
from step.views.step_view import StepListView, StepDetailView, StepUpdateView, StepDeleteView, StepCreateView
from step.views.text_view import TextListView, TextDetailView, TextCreateView, TextUpdateView, TextDeleteView
from step.views.video_view import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView

app_name = 'step'

urlpatterns = [
    path('steps/', StepListView.as_view(), name='stepmodel_list'),
    path('step/<int:pk>/', StepDetailView.as_view(), name='stepmodel_detail'),
    path('step/create/text/', StepCreateView.as_view(), name='stepmodel_text_create'),
    path('step/create/video/', StepCreateView.as_view(), name='stepmodel_video_create'),
    path('step/create/quiz/', StepCreateView.as_view(), name='stepmodel_quiz_create'),
    path('step/<int:pk>/update/', StepUpdateView.as_view(), name='stepmodel_update'),
    path('step/<int:pk>/delete/', StepDeleteView.as_view(), name='stepmodel_delete'),

    path('videos/', VideoListView.as_view(), name='videomodel_list'),
    path('video/<int:pk>/', VideoDetailView.as_view(), name='videomodel_detail'),
    path('video/create/', VideoCreateView.as_view(), name='videomodel_create'),
    path('video/<int:pk>/update/', VideoUpdateView.as_view(), name='videomodel_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='videomodel_delete'),

    path('texts/', TextListView.as_view(), name='textmodel_list'),
    path('text/<int:pk>/', TextDetailView.as_view(), name='textmodel_detail'),
    path('text/create/', TextCreateView.as_view(), name='textmodel_create'),
    path('text/<int:pk>/update/', TextUpdateView.as_view(), name='textmodel_update'),
    path('text/<int:pk>/delete/', TextDeleteView.as_view(), name='textmodel_delete'),

    path('files/', FileListView.as_view(), name='filemodel_list'),
    path('file/<int:pk>/', FileDetailView.as_view(), name='filemodel_detail'),
    path('file/create/', FileCreateView.as_view(), name='filemodel_create'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='filemodel_update'),
    path('file/<int:pk>/delete/', FileDeleteView.as_view(), name='filemodel_delete')
]

modules/views/chapters.py
import re

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.functional import cached_property
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from view_breadcrumbs import DetailBreadcrumbMixin, ListBreadcrumbMixin, CreateBreadcrumbMixin, DeleteBreadcrumbMixin, \
    UpdateBreadcrumbMixin
from modules.forms.chapters_form import ChaptersForm
from modules.models import ChapterModel, CourseModel
from step.models import StepModel

# ChaptersListView здесь создана только для работы DetailBreadcrumbMixin, т.к. он наследуется от ListBreadcrumbMixin и
# без него не работают хлебные крошки.
class ChaptersListView(ListBreadcrumbMixin, PermissionRequiredMixin, ListView):
    model = ChapterModel
    template_name = 'chapters/chapters_list.html'
    context_object_name = 'chapters'
    ordering = ("-create_at",)
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class ChapterCreateView(CreateBreadcrumbMixin, PermissionRequiredMixin, CreateView):
    template_name = "chapters/chapter_create.html"
    model = ChapterModel
    form_class = ChaptersForm
    course = None
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_initial(self):
        self.course = self.request.GET.get('course_pk')
        return {'course': self.course}

    def form_valid(self, form):
        form.instance.course = CourseModel.objects.get(id=self.course)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("modules:coursemodel_detail", kwargs={"pk": self.object.course.pk})


class ChapterDetailView(DetailBreadcrumbMixin, PermissionRequiredMixin, DetailView):
    model = ChapterModel
    context_object_name = 'chapter'
    template_name = 'chapters/chapter_detail.html'
    home_path = reverse_lazy('modules:moderator_page')

    @cached_property
    def crumbs(self):
        chapter = self.get_object()
        course = chapter.course
        module = course.module_id


        return [
            (module._meta.verbose_name_plural, reverse_lazy("modules:modulemodel_list")),
            (module.title, reverse_lazy("modules:modulemodel_detail", kwargs={"pk": module.pk})),
            (course.title, reverse_lazy("modules:coursemodel_detail", kwargs={"pk": chapter.course.pk})),
            (chapter.title, reverse_lazy("modules:chaptermodel_detail", kwargs={"pk": chapter.pk})),
        ]

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['steps'] = StepModel.objects.filter(chapter=self.object.id)
        return context

    def get_success_url(self):
        return reverse("modules:coursemodel_detail", kwargs={"pk": self.object.course.pk})


class ChapterUpdateView(UpdateBreadcrumbMixin, PermissionRequiredMixin, UpdateView):
    model = ChapterModel
    form_class = ChaptersForm
    context_object_name = 'chapter'
    template_name = 'chapters/chapter_update.html'
    home_path = reverse_lazy('modules:moderator_page')

    @cached_property
    def crumbs(self):
        course = self.get_object().course
        module = course.module_id

        return [
            (module._meta.verbose_name_plural, reverse_lazy("modules:modulemodel_list")),
            (module.title, reverse_lazy("modules:modulemodel_detail", kwargs={"pk": module.pk})),
            (course.title, reverse_lazy("modules:coursemodel_detail", kwargs={"pk": course.pk})),
        ] + super().crumbs

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_success_url(self):
        return reverse("modules:coursemodel_detail", kwargs={"pk": self.object.course.pk})


class ChapterDeleteView(DeleteBreadcrumbMixin, PermissionRequiredMixin, DeleteView):
    model = ChapterModel
    template_name = "chapters/chapter_delete.html"
    context_object_name = 'chapter'
    success_url = reverse_lazy("modules:chapters_list")
    home_path = reverse_lazy('modules:moderator_page')

    @cached_property
    def crumbs(self):
        course = self.get_object().course
        module = course.module_id

        return [
            (module._meta.verbose_name_plural, reverse_lazy("modules:modulemodel_list")),
            (module.title, reverse_lazy("modules:modulemodel_detail", kwargs={"pk": module.pk})),
            (course.title, reverse_lazy("modules:coursemodel_detail", kwargs={"pk": course.pk})),
        ] + super().crumbs

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_success_url(self):
        return reverse("modules:coursemodel_detail", kwargs={"pk": self.object.course.pk})

    def form_valid(self, form):
        chapter = self.get_object()
        course = chapter.course
        response = super().form_valid(form)
        self.update_serial_numbers(course)
        return response

    def update_serial_numbers(self, course):
        chapters = ChapterModel.objects.filter(course=course).order_by('serial_number')
        current_serial_number = 1
        for chapter in chapters:
            if chapter.serial_number != current_serial_number:
                chapter.serial_number = current_serial_number
                chapter.save()
            current_serial_number += 1


class ChapterChangeStepsOrderView(PermissionRequiredMixin, View):
    template_name = 'chapters/change_steps_order.html'

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get(self, request, *args, **kwargs):
        chapter = ChapterModel.objects.get(pk=kwargs['pk'])
        steps = StepModel.objects.filter(chapter=chapter)
        context = {
            'chapter': chapter,
            'steps': steps,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        chapter = get_object_or_404(ChapterModel, pk=kwargs['pk'])
        data = self.request.POST
        new_serial_numbers = {}
        for i in data:
            if "pk" in i:
                step_id = i.split("_")[1]
                new_serial_numbers[step_id] = data[i]
        steps = StepModel.objects.filter(chapter=chapter)
        unique_numbers = set(new_serial_numbers.values())

        if len(unique_numbers) < len(new_serial_numbers):
            messages.error(request, 'Выберите разные порядковые номера для глав.')
        else:
            for step_id, new_number in new_serial_numbers.items():
                step = steps.get(id=step_id)
                step.serial_number = new_number
                step.save()

        return redirect('modules:chaptermodel_detail', pk=kwargs['pk'])

modules/views/teachers.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from view_breadcrumbs import DetailBreadcrumbMixin, ListBreadcrumbMixin, CreateBreadcrumbMixin, DeleteBreadcrumbMixin, \
    UpdateBreadcrumbMixin
from modules.forms.teachers_form import TeacherForm
from modules.models import TeacherModel


class TeachersListView(ListBreadcrumbMixin, PermissionRequiredMixin, ListView):
    model = TeacherModel
    template_name = 'teachers/teachers_list.html'
    context_object_name = 'teachers'
    ordering = ("-create_at",)
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class TeacherCreateView(CreateBreadcrumbMixin, PermissionRequiredMixin, CreateView):
    template_name = "teachers/teacher_create.html"
    model = TeacherModel
    form_class = TeacherForm
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_success_url(self):
        return reverse("modules:teachermodel_detail", kwargs={"pk": self.object.pk})


class TeacherDetailView(DetailBreadcrumbMixin, PermissionRequiredMixin, DetailView):
    model = TeacherModel
    context_object_name = 'teacher'
    template_name = 'teachers/teacher_detail.html'
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class TeacherUpdateView(UpdateBreadcrumbMixin, PermissionRequiredMixin, UpdateView):
    model = TeacherModel
    form_class = TeacherForm
    context_object_name = 'teacher'
    template_name = 'teachers/teacher_update.html'
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_success_url(self):
        return reverse("modules:teachermodel_list")


class TeacherDeleteView(DeleteBreadcrumbMixin, PermissionRequiredMixin, DeleteView):
    model = TeacherModel
    template_name = "teachers/teacher_delete.html"
    context_object_name = 'teacher'
    success_url = reverse_lazy("modules:teachermodel_list")
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

templates/modules/module_create.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}Создать модуль{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h1>{% trans 'Add module:' %}</h1>
                {% trans 'Add' as button_text_add %}
                {% include "partials/form.html" with button_text=button_text_add %}
            </div>
        </div>
    </div>
{% endblock %}

templates/modules/module_delete.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load static view_breadcrumbs %}
{% block title %}{% trans 'Delete module' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card">
        <div class="card-body">
            <p class="card-text">
                {% blocktrans with title=module.title %}
                Are you sure you want to delete the module
                <span class="text-danger"> {{ title }}</span>?
                {% endblocktrans %}
            </p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="delete" class="btn btn-danger me-4" value="yes">{% trans 'Yes' %}</button>
                <a class="btn btn-primary" href="{% url "modules:modulemodel_list" %}" id="cancel-button">{% trans 'No' %}</a>
            </form>
        </div>
    </div>
    <script src="{% static 'js/delete_button_func.js' %}"></script>
{% endblock %}

templates/modules/module_detail.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}{{ module.title }}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card my-4">
        <div class="card-body">
            {% include 'partials/main_block.html' with data=module %}
            <div class="d-flex justify-content-end">
                <a href="{% url 'modules:modulemodel_update' module.id %}"
                   class="btn btn-info btn-sm mx-3">{% trans 'Change' %}</a>
                <a href="{% url 'modules:modulemodel_delete' module.id %}"
                   class="btn btn-danger btn-sm " style="margin-right: 0.8rem">{% trans 'Delete' %}</a>
            </div>
        </div>
    </div>
    <div class="card mb-5">
        <div class="card-body">
            <h2 class="my-3">{% blocktrans with title=module.title %}List of {{ title }} module's courses{% endblocktrans %}</h2>
            <a href="{% url 'modules:coursemodel_create' %}?module_pk={{ module.pk }}" class="btn btn-primary my-3">
                {% trans 'Add course' %}</a>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>{% trans 'Title' %}</th>
                    <th class="text-end">{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for course in courses|dictsort:"id" %}
                    <tr>
                        <td>{{ course.id }}</td>
                        <td><a href="{% url 'modules:coursemodel_detail' course.id %}">{{ course.title }}</a></td>
                        <td class="text-end">
                            <div class="btn-group">
                                <a href="{% url 'modules:coursemodel_update' course.id %}"
                                   class="btn btn-info btn-sm mx-3">{% trans 'Change' %}</a>
                                <a href="{% url 'modules:coursemodel_delete' course.id %}"
                                   class="btn btn-danger btn-sm">{% trans 'Delete' %}</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/modules/module_update.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}Редактировать модуль{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h1>{% trans 'Change module' %}</h1>
                {% trans 'Edit' as button_text_change %}
                {% include "partials/form.html" with button_text=button_text_change %}
            </div>
        </div>
    </div>
{% endblock %}

templates/modules/modules_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удаление модуля{% endblock %}
{% block content %}
    <div class="d-block">
        <p class="card-text">Вы точно хотите удалить модуль:<span class="text-danger"> {{ module.title }}</span>
        </p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="btn-group" role="group">
            <button type="submit" name="delete" class="btn btn-danger" value="yes">Да</button>
        </div>
        <a class="btn btn-primary" href="{% url "modules:module_detail" module.pk %}">Нет</a>
    </form>
{% endblock %}

templates/modules/modules_detail.html
{% extends 'base.html' %}
{% block title %}Программа курса{% endblock %}
{% block content %}
    {% include 'partials/main_block.html' %}

    <div class="container">
        <p>Данный курс был составлен: <a href="{% url 'modules:teacher_detail' %}">Учитель 1,</a> <a
                href="{% url 'modules:teacher_detail' %}">Учитель 2</a></p>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        Глава #1
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">

                        <div class="accordion" id="sub-accordionExample">
                            <div>
                                <h1></h1>
                                <ul class="ul_tree p-has-headers">
                                    <li class="li_tree">
                                        <a href="{% url 'modules:step_text' %}" class="header">Пример Текста</a>
                                    </li>
                                    <li class="li_tree">
                                        <a href="{% url 'modules:step_video' %}" class="header">Пример Видео</a>
                                    </li>
                                    <li class="li_tree">
                                        <a href="{% url 'modules:step_file' %}" class="header">Пример Файла</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Глава #2 Тесты
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">

                        <div class="accordion" id="sub-accordionExample">
                            <div>
                                <h1></h1>
                                <ul class="ul_tree p-has-headers">
                                    <li class="li_tree">
                                        <a href="{% url 'modules:test_bim' %}" class="header">Пример Теста</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/modules/modules_list.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}Модули{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="px-sm-0 px-md-5">
        <div class="card mb-5">
            <div class="card-body">
                <div class="card-header">
                    <h2>{% trans 'Modules list' %}</h2>
                </div>
                <a href="{% url 'modules:modulemodel_create' %}" class="btn btn-primary my-3">{% trans 'Add modules' %}</a>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{% trans 'Title' %}</th>
                            <th class="text-end">{% trans 'Actions' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for module in modules|dictsort:"id" %}
                            <tr>
                                <td>{{ module.id }}</td>
                                <td><a href="{% url 'modules:modulemodel_detail' module.id %}">{{ module.title }}</a>
                                </td>
                                <td class="text-end">
                                    <div class="btn-group">
                                        <a href="{% url 'modules:modulemodel_update' module.id %}"
                                           class="btn btn-info btn-sm mx-3">{% trans 'Change' %}</a>
                                        <a href="{% url 'modules:modulemodel_delete' module.id %}"
                                           class="btn btn-danger btn-sm">{% trans 'Delete' %}</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}