accessibleBIM/urls.py
from allauth.urls import provider_urlpatterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from accessibleBIM import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/', include('allauth.socialaccount.urls')),
    path('accounts/', include(provider_urlpatterns)),
] + i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('front.urls')),
    path('', include('accounts.urls')),
    path('moderator/', include('modules.urls')),
    path('moderator/', include('progress.urls')),
    path('moderator/', include('step.urls')),
    path('moderator/', include('subscription.urls')),
    path('quiz_bim/', include('quiz_bim.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('statistics/', include('reports.urls')),
    path('moderator/', include('content.urls')),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "front.views.errors_handler.page_not_found_view"
handler403 = "front.views.errors_handler.permission_denied_view"
handler500 = "front.views.errors_handler.server_error_view"

step/urls.py
from django.urls import path

from step.views.file_view import FileListView, FileDetailView, FileCreateView, FileUpdateView, FileDeleteView
from step.views.step_view import StepListView, StepDetailView, StepUpdateView, StepDeleteView, StepCreateView
from step.views.text_view import TextListView, TextDetailView, TextCreateView, TextUpdateView, TextDeleteView
from step.views.video_view import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView

app_name = 'step'

urlpatterns = [
    path('steps/', StepListView.as_view(), name='stepmodel_list'),
    path('step/<int:pk>/', StepDetailView.as_view(), name='stepmodel_detail'),
    path('step/create/text/', StepCreateView.as_view(), name='stepmodel_text_create'),
    path('step/create/video/', StepCreateView.as_view(), name='stepmodel_video_create'),
    path('step/create/quiz/', StepCreateView.as_view(), name='stepmodel_quiz_create'),
    path('step/<int:pk>/update/', StepUpdateView.as_view(), name='stepmodel_update'),
    path('step/<int:pk>/delete/', StepDeleteView.as_view(), name='stepmodel_delete'),

    path('videos/', VideoListView.as_view(), name='videomodel_list'),
    path('video/<int:pk>/', VideoDetailView.as_view(), name='videomodel_detail'),
    path('video/create/', VideoCreateView.as_view(), name='videomodel_create'),
    path('video/<int:pk>/update/', VideoUpdateView.as_view(), name='videomodel_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='videomodel_delete'),

    path('texts/', TextListView.as_view(), name='textmodel_list'),
    path('text/<int:pk>/', TextDetailView.as_view(), name='textmodel_detail'),
    path('text/create/', TextCreateView.as_view(), name='textmodel_create'),
    path('text/<int:pk>/update/', TextUpdateView.as_view(), name='textmodel_update'),
    path('text/<int:pk>/delete/', TextDeleteView.as_view(), name='textmodel_delete'),

    path('files/', FileListView.as_view(), name='filemodel_list'),
    path('file/<int:pk>/', FileDetailView.as_view(), name='filemodel_detail'),
    path('file/create/', FileCreateView.as_view(), name='filemodel_create'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='filemodel_update'),
    path('file/<int:pk>/delete/', FileDeleteView.as_view(), name='filemodel_delete')
]

step/models/file.py
import os

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from modules.models import AbstractModel


def file_upload_to(instance, filename):
    return os.path.join('steps', 'files', filename)


class FileModel(AbstractModel):
    file_title = models.CharField(max_length=250, blank=True, null=True, verbose_name=_('File title'))
    lesson_file = models.FileField(upload_to=file_upload_to, blank=True, null=True, verbose_name=_('Lesson file'))

    def get_absolute_url(self):
        return reverse('step:filemodel_list')

    def __str__(self):
        return f'Файл {self.id} {self.file_title}'

    class Meta:
        db_table = 'files'
        verbose_name = _('File')
        verbose_name_plural = _('Files')

step/models/text.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from modules.models import AbstractModel


class TextModel(AbstractModel):
    text_title = models.CharField(max_length=250, blank=True, null=True, verbose_name=_('Text title'))
    text_description = models.CharField(max_length=1500, blank=True, null=True, verbose_name=_('Text description'))
    content = models.TextField(max_length=100000, blank=True, null=True, verbose_name=_('Text content'))

    def get_absolute_url(self):
        return reverse("step:text_list")

    def __str__(self):
        return f'Текст {self.id} {self.text_title}'

    class Meta:
        db_table = 'texts'
        verbose_name = _('Text')
        verbose_name_plural = _('Texts')

step/views/file_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from view_breadcrumbs import DetailBreadcrumbMixin, ListBreadcrumbMixin, CreateBreadcrumbMixin, DeleteBreadcrumbMixin, \
    UpdateBreadcrumbMixin
from step.forms.file_form import FileForm
from step.models import FileModel


class FileListView(ListBreadcrumbMixin, PermissionRequiredMixin, ListView):
    model = FileModel
    template_name = 'steps/file/file_list.html'
    context_object_name = 'files'
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class FileDetailView(DetailBreadcrumbMixin, PermissionRequiredMixin, DetailView):
    model = FileModel
    queryset = FileModel.objects.all()
    template_name = "steps/file/file_detail.html"
    context_object_name = 'file'
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class FileCreateView(CreateBreadcrumbMixin, PermissionRequiredMixin, CreateView):
    model = FileModel
    form_class = FileForm
    template_name = "steps/file/file_create.html"
    success_url = reverse_lazy('step:filemodel_list')
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

class FileUpdateView(UpdateBreadcrumbMixin, PermissionRequiredMixin, UpdateView):
    model = FileModel
    form_class = FileForm
    template_name = 'steps/file/file_update.html'
    success_url = reverse_lazy('step:filemodel_list')
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser


class FileDeleteView(DeleteBreadcrumbMixin, PermissionRequiredMixin, DeleteView):
    model = FileModel
    template_name = 'steps/file/file_delete.html'
    success_url = reverse_lazy('step:filemodel_list')
    home_path = reverse_lazy('modules:moderator_page')

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

step/views/step_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.functional import cached_property
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.urls import reverse, reverse_lazy
from modules.models import ChapterModel
from step.models import FileModel
from step.models.step import StepModel
from view_breadcrumbs import DetailBreadcrumbMixin, ListBreadcrumbMixin, DeleteBreadcrumbMixin

from step.forms.step_multi_form import MultiStepVideoForm, MultiStepQuizForm, MultiStepTextForm,\
    MultiStepTextUpdateForm, MultiStepVideoUpdateForm
from step.step_validators import validate_empty, validate_empty_for_update


# Представление StepListView в текущем состоянии не актуально. Добавлять проверку на разрешения в него не стал.
class StepListView(ListBreadcrumbMixin, ListView):
    model = StepModel
    template_name = 'steps/step/step_list.html'
    context_object_name = 'steps'
    success_url = reverse_lazy('modules:index')
    home_path = reverse_lazy('modules:moderator_page')


class StepDetailView(DetailBreadcrumbMixin, PermissionRequiredMixin, DetailView):
    model = StepModel
    queryset = StepModel.objects.all()
    context_object_name = 'step'
    template_name = "steps/step/step_detail.html"
    home_path = reverse_lazy('modules:moderator_page')

    @cached_property
    def crumbs(self):
        step = self.get_object()
        chapter = step.chapter
        course = chapter.course
        module = course.module_id

        return [
            (module._meta.verbose_name_plural, reverse_lazy("modules:modulemodel_list")),
            (module.title, reverse_lazy("modules:modulemodel_detail", kwargs={"pk": module.pk})),
            (course.title, reverse_lazy("modules:coursemodel_detail", kwargs={"pk": course.pk})),
            (chapter.title, reverse_lazy("modules:chaptermodel_detail", kwargs={"pk": chapter.pk})),
            (step.title, reverse_lazy("modules:chaptermodel_detail", kwargs={"pk": step.chapter.pk})),
        ]

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        step = context['step']
        files = FileModel.objects.filter(step=step)
        context['files'] = files
        return context


class StepCreateView(PermissionRequiredMixin, CreateView):
    template_name = "steps/step/step_create.html"
    chapter = None
    home_path = reverse_lazy('modules:moderator_page')

    def get_form_class(self):
        url_path = self.request.path.split('/')
        match url_path[-2]:
            case 'text':
                return MultiStepTextForm
            case 'video':
                return MultiStepVideoForm
            case "quiz":
                return MultiStepQuizForm

    def form_valid(self, form):
        url_path = self.request.path.split('/')
        error_messages = validate_empty(self, form, url_path[-2])
        if error_messages:
            return render(self.request, "steps/step/step_create.html", context={
                "form": form,
                "error_messages": error_messages,
            })
        match url_path[-2]:
            case 'text':
                return self.save_step_text_model(form)
            case 'video':
                return self.save_step_video_model(form)
            case 'quiz':
                return self.save_step_quiz_model(form)

    def save_step_text_model(self, form):
        step = form['step'].save(commit=False)
        step.lesson_type = 'text'
        step.chapter = get_object_or_404(ChapterModel, pk=self.chapter)
        if form['text'].cleaned_data['text_title']:
            text = form['text'].save()
        else:
            text = form['step'].cleaned_data['text']
        step.text = text
        self.work_with_files(step, form)
        return redirect("modules:chaptermodel_detail", self.chapter)

    def save_step_video_model(self, form):
        step = form['step'].save(commit=False)
        step.lesson_type = 'video'
        step.chapter = get_object_or_404(ChapterModel, pk=self.chapter)
        if form['video'].cleaned_data['video_title']:
            video = form['video'].save()
        else:
            video = form['step'].cleaned_data['video']
        step.video = video
        self.work_with_files(step, form)
        return redirect("modules:chaptermodel_detail", self.chapter)

    def save_step_quiz_model(self, form):
        step = form['step'].save(commit=False)
        step.lesson_type = 'test'
        step.chapter = get_object_or_404(ChapterModel, pk=self.chapter)
        if form['quiz'].cleaned_data['title']:
            test = form['quiz'].save()
        else:
            test = form['step'].cleaned_data['test']
        step.test = test
        step.save()
        return redirect("quiz_bim:quizbim_detail", test.pk)

    def work_with_files(self, step, form):
        step.save()
        if form['step'].cleaned_data['file']:
            file_loaded = form['step'].cleaned_data['file']
            step.file.set(file_loaded, )
        if form['file'].cleaned_data['lesson_file']:
            file_download = form['file'].save()
            step.file.add(file_download, )
        return step

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_initial(self):
        super().get_initial()
        self.chapter = self.request.GET.get('chapter_pk')
        return {'chapter': self.chapter}


class StepUpdateView(PermissionRequiredMixin, UpdateView):
    model = StepModel
    template_name = 'steps/step/step_update.html'
    home_path = reverse_lazy('modules:moderator_page')
    chapter = None

    @cached_property
    def crumbs(self):
        chapter = self.get_object().chapter
        course = chapter.course
        module = course.module_id

        return [
            (module._meta.verbose_name_plural, reverse_lazy("modules:modulemodel_list")),
            (module.title, reverse_lazy("modules:modulemodel_detail", kwargs={"pk": module.pk})),
            (course.title, reverse_lazy("modules:coursemodel_detail", kwargs={"pk": course.pk})),
            (chapter.title, reverse_lazy("modules:chaptermodel_detail", kwargs={"pk": chapter.pk}))
        ] + super().crumbs

    def get_initial(self):
        self.chapter = self.request.GET.get('chapter_pk')
        return {'chapter': self.chapter}

    def get_form_kwargs(self):
        kwargs = super(StepUpdateView, self).get_form_kwargs()
        match self.object.lesson_type:
            case 'text':
                kwargs.update(instance={
                    'step': self.object,
                    'text': self.object.text,
                })
            case 'video':
                kwargs.update(instance={
                    'step': self.object,
                    'video': self.object.video,
                })
            case "test":
                kwargs.update(instance={
                    'step': self.object,
                    'test': self.object.test,
                })
        return kwargs

    def get_form_class(self):
        match self.object.lesson_type:
            case 'text':
                return MultiStepTextUpdateForm
            case 'video':
                return MultiStepVideoUpdateForm
            case "test":
                return MultiStepQuizForm

    def form_valid(self, form):
        step = form['step'].save(commit=False)
        error_messages = validate_empty_for_update(form, self.object.lesson_type)
        if error_messages:
            return render(self.request, "steps/step/step_update.html", context={
                "form": form,
                "error_messages": error_messages,
            })
        match self.object.lesson_type:
            case 'text':
                self.update_step_text_model(step, form)
            case 'video':
                self.update_step_video_model(step, form)
            case 'test':
                self.update_step_quiz_model(step, form)
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form_class = self.get_form_class()
        return form_class(**self.get_form_kwargs())

    def update_step_text_model(self, step, form):
        if form['step'].cleaned_data['text']:
            step.text = form['step'].cleaned_data['text']
        self.work_with_files(step, form)

    def update_step_video_model(self, step, form):
        if form['step'].cleaned_data['video']:
            step.video = form['step'].cleaned_data['video']
        self.work_with_files(step, form)

    def update_step_quiz_model(self, step, form):
        if form['quiz'].cleaned_data['title']:
            step.test = form['quiz'].save()
        step.save()
        return reverse("modules:chaptermodel_detail", kwargs={"pk": step.chapter.id})

    def work_with_files(self, step, form):
        step.save()
        if form['step'].cleaned_data['file']:
            file_loaded = form['step'].cleaned_data['file']
            step.file.set(file_loaded, )
        if form['file'].cleaned_data['lesson_file']:
            file_download = form['file'].save()
            step.file.add(file_download, )
        return reverse("modules:chaptermodel_detail", kwargs={"pk": step.chapter.id})

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='moderators').exists() or user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['text'], context['video'], context['test'] = self.object.text, self.object.video, self.object.test
        return context


    def get_success_url(self):

templates/steps/file/file_create.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}{% trans 'Add file' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    {% if perms.step.add_textmodel %}
        <div class="card mb-5">
            <div class="card-body">
                <div>
                    <div class="container my-5">
                        <div class="card-header">
                            <h2>{% trans 'Add file' %}:</h2>
                        </div>
                        <div>
                            {% trans 'Add' as button_text_add %}
                            {% include "partials/form.html" with button_text=button_text_add %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/steps/file/file_delete.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load static view_breadcrumbs %}
{% block title %}{% trans 'Delete file' %}Удалить файл{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card">
        <div class="card-body">
            <p class="card-text">
                {% blocktrans with title=filemodel.file_title %}
                Are you sure you want to delete the file
                <span class="text-danger"> {{ title }}</span>?
                {% endblocktrans %}
            </p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="delete" class="btn btn-danger me-4" value="yes">{% trans 'Yes' %}</button>
                <a href="#" class="btn btn-secondary
                    mx-3" id="cancel-button">{% trans 'No' %}</a>
            </form>
        </div>
    </div>
    <script src="{% static 'js/delete_button_func.js' %}"></script>
{% endblock %}

templates/steps/file/file_detail.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}{% trans 'View file' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    {% if request.user.is_authenticated %}
        <div class="card mb-5">
            <div class="card-body">
                <div class="card-header">
                    <h2>File: {{ file.file_title }}</h2>
                </div>
                <a href="{{ file.lesson_file.url }}" download class="btn btn-primary my-3 me-3">{% trans 'Download file' %}</a>
                <a href="{% url 'step:filemodel_list' %}" class="btn btn-secondary">{% trans 'Back to files list' %}</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/steps/file/file_list.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}{% trans 'Files list' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    <div class="card mb-5">
        <div class="card-body">
            <div class="card-header">
                <h1>{% trans 'Files list' %}</h1>
            </div>
            {% if perms.step.add_filemodel %}
                <a href="{% url 'step:filemodel_create' %}" class="btn btn-primary my-3">{% trans 'Add' %}</a>
            {% endif %}
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>{% trans 'Title' %}</th>
                    <th class="text-end">{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for file in files|dictsort:"id" %}
                    <tr>
                        <td>{{ file.id }}</td>
                        <td>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'step:filemodel_detail' file.id %}">{{ file.file_title }}</a>
                            {% endif %}
                        </td>
                        <td class="text-end">
                            {% if perms.step.change_filemodel %}
                                <a href="{% url 'step:filemodel_update' file.id %}"
                                   class="btn btn-info btn-sm mx-2">{% trans 'Change' %}</a>
                            {% endif %}
                            {% if perms.step.delete_filemodel %}
                                <a href="{% url 'step:filemodel_delete' file.id %}"
                                   class="btn btn-danger btn-sm">{% trans 'Delete' %}</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/steps/file/file_update.html
{% extends 'moderator_page.html' %}
{% load i18n %}
{% load view_breadcrumbs %}
{% block title %}{% trans 'Edit file' %}{% endblock %}
{% block moderator_interface %}
    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    {% if perms.step.add_textmodel %}
        <div class="card mb-5">
            <div class="card-body">
                <div>
                    <div class="container my-5">
                        <div class="card-header">
                            <h2>{% trans 'Edit file' %}:</h2>
                        </div>
                        <div>
                            {% trans 'Edit' as button_text_edit %}
                            {% include "partials/form.html" with button_text=button_text_edit %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}